insert into estados (id,estado,sigla) values (1,'Acre','AC');
insert into estados (id,estado,sigla) values (2,'Alagoas','AL');
insert into estados (id,estado,sigla) values (3,'Amapá','AP');
insert into estados (id,estado,sigla) values (4,'Amazonas','AM');
insert into estados (id,estado,sigla) values (5,'Bahia','BA');
insert into estados (id,estado,sigla) values (6,'Ceará','CE');
insert into estados (id,estado,sigla) values (7,'Distrito Federal','DF');
insert into estados (id,estado,sigla) values (8,'Espirito Santo','ES');
insert into estados (id,estado,sigla) values (9,'Goiás','GO');
insert into estados (id,estado,sigla) values (10,'Maranhão','MA');
insert into estados (id,estado,sigla) values (11,'Mato Grosso','MT');
insert into estados (id,estado,sigla) values (12,'Mato Grosso Do Sul','MS');
insert into estados (id,estado,sigla) values (13,'Minas Gerais','MG');
insert into estados (id,estado,sigla) values (14,'Pará','PA');
insert into estados (id,estado,sigla) values (15,'Paraíba','PB');
insert into estados (id,estado,sigla) values (16,'Paraná','PR');
insert into estados (id,estado,sigla) values (17,'Pernambuco','PE');
insert into estados (id,estado,sigla) values (18,'Piauí','PI');
insert into estados (id,estado,sigla) values (19,'Rio de Janeiro','RJ');
insert into estados (id,estado,sigla) values (20,'Rio Grande do Norte','RN');
insert into estados (id,estado,sigla) values (21,'Rio Grande do Sul','RS');
insert into estados (id,estado,sigla) values (22,'Rondônia','RO');
insert into estados (id,estado,sigla) values (23,'Roraima','RR');
insert into estados (id,estado,sigla) values (24,'Santa Catarina','SC');
insert into estados (id,estado,sigla) values (25,'São Paulo','SP');
insert into estados (id,estado,sigla) values (26,'Sergipe','SE');
insert into estados (id,estado,sigla) values (27,'Tocantins','TO');
insert into cidades (id,nomedacidade,estado_id) values (1,'Vitória da Conquista',5);
insert into cidades (id,nomedacidade,estado_id) values (2,'Guarulhos',25);
insert into enderecos (id,logradouro,bairro,cep,complemento,cidade_id,estado_id) values (1,'Av. Luís Eduardo Magalhães', 'Candeias','45055-420','Faculdade',1,5);